name = "pic_examples"
version = "0.1.0"
license = "MIT"
author = "JorgeG94"
maintainer = "jorgegalvez1694@gmail.com"
copyright = "Copyright 2024, JorgeG94"
[preprocess]
[preprocess.cpp]
suffixes = ["F90", "f90"]

[[executable]]
name = "minimal_example"
source-dir = "minimal_example"
main = "minimal.f90"

[[executable]]
name = "pic_array"
source-dir = "pic_array"
main = "main.f90"

[[executable]]
name = "pic_logger"
source-dir = "pic_logger"
main = "main.f90"

[[executable]]
name = "pic_timer"
source-dir = "pic_timer"
main = "main.f90"

[[executable]]
name = "pic_flops"
source-dir = "pic_flops"
main = "main.f90"

[[executable]]
name = "pic_flop_rate"
source-dir = "pic_flop_rate"
main = "main.f90"

[[executable]]
name = "pic_sort"
source-dir = "pic_sort"
main = "main.f90"
[build]
auto-executables = true
auto-tests = false
#auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

[dependencies]
pic = { git = "https://github.com/JorgeG94/pic.git", branch = "main"}

[extra.fortitude.check]
select = ["C", "E", "S"]
ignore = ["C003"]
line-length = 132
per-file-ignores = { "pic_blas_interfaces.F90" = ["C071"] }
